name: Build APK - El Mariano

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-venv python3-pip

    - name: Install Android SDK
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools

        echo "Bajando SDK..."
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip

        echo "Descomprimiendo..."
        unzip tools.zip -d temp
        rm tools.zip

        echo "Moviendo contenido a 'latest'..."
        mkdir -p latest
        mv temp/cmdline-tools/* latest/
        rm -rf temp

        echo "Exportando rutas..."
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Install Buildozer
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install buildozer cython wheel

    - name: Build APK
      run: |
        source venv/bin/activate
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: el-mariano-apk
        path: ./bin/*.apk
