name: Build APK - El Mariano

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "buildozer.spec"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build debug APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        env:
          USER: runner
        with:
          workdir: .
          buildozer_version: latest
          command: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: elmariano-debug-apk
          path: bin/*.apk
