name: Build APK

on:
  workflow_dispatch:        # para lanzarlo a mano desde la pestaña "Actions"
  push:
    branches:
      - main                # opcional: build cada push a main

jobs:
  build:
    runs-on: ubuntu-latest

    # esta env se pasa al contenedor de buildozer y evita el input [y/n]
    env:
      BUILDOZER_ALLOW_ROOT: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Acción oficial para usar Buildozer dentro de Docker
      - name: Build APK with Buildozer (Docker)
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: el-mariano-apk
          path: bin/*.apk
