name: Build APK - El Mariano

on:
  push:
    paths:
      - "**/*.py"
      - "buildozer.spec"
      - ".github/workflows/Build.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # importante: 22.04, no 24.04

    env:
      USER: runner          # evita el error de chown "invalid user: user"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build debug APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: el-mariano-apk
          path: bin/*.apk
